services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - 8002:8002
    env_file:
      .env
      # networks:
      # - behind-nginx
    container_name: grocery-shop-backend

# networks:
#     behind-nginx:
#         external:
#             name: behind-nginx-network
