"""test use of commonsqlmodel

Revision ID: 04a8ff209839
Revises: 0e1d0306eaf2
Create Date: 2024-07-04 15:08:43.662337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '04a8ff209839'
down_revision = '0e1d0306eaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('total_item', sa.Integer(), nullable=True),
    sa.Column('total_payable_price', sa.Float(), nullable=True),
    sa.Column('order_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_status', sa.Enum('PROCESSING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('order')
    # ### end Alembic commands ###