"""OrderItemAdded

Revision ID: 2b4a4c33728e
Revises: c9fa24246a4c
Create Date: 2023-03-16 21:18:09.672368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2b4a4c33728e'
down_revision = 'c9fa24246a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    # ### end Alembic commands ###