"""orderitem change

Revision ID: 463ec26568e5
Revises: 9b6de85fce01
Create Date: 2023-03-17 14:39:47.102506

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '463ec26568e5'
down_revision = '9b6de85fce01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('orderitem', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderitem', 'product', ['product_id'], ['id'])
    op.drop_column('orderitem', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'product_id')
    op.drop_column('orderitem', 'count')
    # ### end Alembic commands ###