"""use of commonsqlmodel

Revision ID: 46adcc2d8967
Revises: 04a8ff209839
Create Date: 2024-07-04 17:30:03.127743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '46adcc2d8967'
down_revision = '04a8ff209839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('coupon', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('coupon', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('shop', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('shop', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('shop', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('shop', 'deleted_at')
    op.drop_column('shop', 'updated_at')
    op.drop_column('shop', 'created_at')
    op.drop_column('product', 'deleted_at')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('order', 'deleted_at')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    op.drop_column('coupon', 'deleted_at')
    op.drop_column('coupon', 'updated_at')
    op.drop_column('coupon', 'created_at')
    # ### end Alembic commands ###