"""test use of commonsqlmodel

Revision ID: 5625551196c0
Revises: 6232284425c0
Create Date: 2024-07-04 15:07:34.348094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5625551196c0'
down_revision = '6232284425c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###