"""user role added

Revision ID: 70bac43b9e52
Revises: f8d206fdef2d
Create Date: 2024-07-04 19:20:35.255549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70bac43b9e52'
down_revision = 'f8d206fdef2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###