"""order order item

Revision ID: 73a959537fb1
Revises: e5a2277a9112
Create Date: 2024-07-04 14:47:59.603123

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '73a959537fb1'
down_revision = 'e5a2277a9112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###