"""category

Revision ID: 8d678e7dadc0
Revises: c8feee136dd1
Create Date: 2024-07-04 14:20:03.166232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8d678e7dadc0'
down_revision = 'c8feee136dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###