"""order added with enum

Revision ID: 92b8cddbdba9
Revises: 76d16c1f48e6
Create Date: 2023-03-16 22:15:11.312351

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '92b8cddbdba9'
down_revision = '76d16c1f48e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'product_id')
    # ### end Alembic commands ###