"""chield renamed to orderitem ok

Revision ID: 9b6de85fce01
Revises: 1c4c9bf95f92
Create Date: 2023-03-17 14:30:46.696562

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b6de85fce01'
down_revision = '1c4c9bf95f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('child_changed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_changed',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='child_changed_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='child_changed_pkey')
    )
    op.drop_table('orderitem')
    # ### end Alembic commands ###