"""order added with enum ok

Revision ID: b4c60dc95322
Revises: 92b8cddbdba9
Create Date: 2023-03-16 22:17:31.744211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b4c60dc95322'
down_revision = '92b8cddbdba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_status', sa.Enum('PROCESSING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###