"""order  item order_id added

Revision ID: c7663b375072
Revises: b4c60dc95322
Create Date: 2023-03-16 22:34:50.453801

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c7663b375072'
down_revision = 'b4c60dc95322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'order_id')
    # ### end Alembic commands ###