"""order  modified and coupone added

Revision ID: f1da6ddd426d
Revises: c7663b375072
Create Date: 2023-03-16 23:03:38.384057

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f1da6ddd426d'
down_revision = 'c7663b375072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='couponstatus'), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('expire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_title'), 'coupon', ['title'], unique=False)
    op.create_table('couponorderlink',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couponorderlink')
    op.drop_index(op.f('ix_coupon_title'), table_name='coupon')
    op.drop_table('coupon')
    # ### end Alembic commands ###